### ISSUE TITLE
None is not of type u'string'

### ISSUE THREAD

**Issue by BurntToast-DFIR** [gcrahay/otx_misp#12]
I am getting the above error whenever I run otx-misp.  I also get it if I invoke the module directly from Python using Python 3 or Python 2.

### Versions

- otx-misp: latest
- PyMISP: latest
- MISP: 2.4.72
- Python:
- Operating system: Ubuntu 16.10

**Comment by jbeley** [comment]
I found that this error was related to events starting with the HTML entity "&quot;". 
I ran a simple MySQL query against my dataset:
UPDATE `events` SET `info` = replace(info, '&quot;', '');
After that "--dedup-titles" option began to work again.

**Comment by SparkyNZL** [comment]
I just tired what you recommended, it did find 158 entries, but this still give the following error when run with --dedupe-titles 
None is not of type 'string'

**Comment by jbeley** [comment]
Are there any other entries that start with another non ASCII characters?
Check your otx feed to see if there are.

**Comment by SparkyNZL** [comment]
should i check the feed or my MISP database ? I did find some starting with # and ( and have removed 

but got the same error then i removed all of the following and it seems to have fixed it :)
  |  [ { } ]  

Cheers

**Comment by SparkyNZL** [comment]
So i think the biggest issue is that when you use the -a flag it add
AlienVault| I think the "|" is playing with the dedup :(

**Comment by SparkyNZL** [comment]
So i have turned Debug on in the DeDupe function, 

this is the out put, bit it looks like its more an issue with the tag now the title ?

------------------------------------------------------------------------------------------------------

{
    "version": "2.4.74", 
    "perm_sync": true
}
{
    "url": "/tags/attachTagToObject", 
    "message": "Cannot attach tag, Event already has the tag attached.", 
    "errors": [
        "Cannot attach tag, Event already has the tag attached."
    ], 
    "name": "Cannot attach tag, Event already has the tag attached."
}
{
    "url": "/tags/attachTagToObject", 
    "message": "Cannot attach tag, Event already has the tag attached.", 
    "errors": [
        "Cannot attach tag, Event already has the tag attached."
    ], 
    "name": "Cannot attach tag, Event already has the tag attached."
}
None is not of type u'string'


-----------------------------------------------------------------------------------------------------------------------------

**Comment by SparkyNZL** [comment]
The error that occurs prior to this is as follows

--------------------------------------------------------------------------------------------------------

The basestring type cannot be instantiated

---------------------------------------------------------------------------------------------------------

**Comment by SparkyNZL** [comment]
From what i can tell the --dedup function of this is broken, as soon as it detects a duplicate it stops with the above (with debug turned on) Is there any chance this can be fixed ? or am i doing something wrong ?

**Comment by SparkyNZL** [comment]
so there seems to be an issue with the misp.add_blar.blar causing the "None is not of type u'string'"  the uses of misp.new.blar.blar works fine and doesnt cause the error, it only causes an error if there is already an event (duplicate) already in the database, i cant tell if this is caused but the fact that misp has had a number of changes recently or not.

**Comment by SparkyNZL** [comment]
Hi, I would really like to fix this error, can you please point me in the right direction, there seems to be an issue with the misp.add_* commands when ever it trys to do this it caused this "None is not of type "String" error. Im not sure if its with otx-misp or with the API. 

Cheers

**Comment by SparkyNZL** [comment]
I have finally fixed this issue.

the latest version of MISP now returns a Sharing Group, this is currntly set to none ! which is what is causing the error. 

I have done a farmers fix, but it works well. what this does is deletes the "SharingGroup" from the list which is compiled. 

if you add the following  at the shown location it should now work
