### ISSUE TITLE
Clarification on usage

### ISSUE THREAD

**Issue by grwerbacher** [gcrahay/otx_misp#3]
Hey there,

I am running into issues running the actual command. Two things occur when I run the command:

1) I get the error time data '2016-05-17T07:07:35' does not match format '%Y-%m-%dT%H:%M:%S.%f'
2) I just get a return value of "Event" on the command line and nothing executes.

Can you please clarify on how to use the command? I'm a little confused on the config file.

Thanks!

**Comment by gcrahay** [comment]
Hi,

1) When I test with the option `--timestamp 2016-05-17T07:07:35`, I can't reproduce the error.
2) Can you test with more verbosity (`-vvv`) and with the `--dry-run` switch (no write to MISP, only prints downloaded Pulses):

``` bash
$ otx-misp -o <otx-key> -s https://misp.example.com/ -m <misp-api-key> --timestamp 2016-05-17T07:07:35 --dry-run -w -vvv
```

Note: the `-w` switch without config file prints the resulting INI file to stdout at the end of the execution.

Sorry for the unclear documentation.

**Comment by grwerbacher** [comment]
This worked and showed me all my pulses, now do I just remove the `--dry-run` in order to import it into MISP, or do I need to add to the command, excluding the optional fields?

**Comment by gcrahay** [comment]
You can remove the `--dry-run`  to create the MISP events. 

If you don't use the `--no-tlp` switch, the MISP user should have the 'Tagger' permission.

**Comment by grwerbacher** [comment]
When I tired running this, this is what occurs:

`# otx-misp -o <my key> -s http://<my URL>/ -m <my misp key> --timestamp 2016-05-17T07:07:35 -w -vvv
Connection to MISP instance: http://<my URL/
## SSH bruteforce logs 2016-06-21 - 2016-06-22
	 - Adding tag: tlp:green
Event`

Then nothing happens after that, any ideas? I'm new to MISP so this might be an error within the application itself

**Comment by gcrahay** [comment]
Could you test again with the `--not-tlp` switch?

What is the role of your MISP user?

**Comment by grwerbacher** [comment]
My MISP user role is Org Admin

**Comment by gcrahay** [comment]
Can you see errors in MISP (Audit => List logs)?

**Comment by grwerbacher** [comment]
Nope there is no errors within MISP

**Comment by gcrahay** [comment]
Can you install and try the branch issue_3 with the `-vvv` option?

**Comment by gcrahay** [comment]
Old issue
