### ISSUE TITLE
Feature-Request: Remember Last Pull 

### ISSUE THREAD

**Issue by giray** [gcrahay/otx_misp#5]
It would be great of otx-misp would keep a state file to keep track of the last 
added event(s), so when you run it again ti wont go through all events.

**Comment by gcrahay** [comment]
Yes, the documentation needs to be improved. You can use a configuration file with the '-c' option:

```
root@misp:~# otx-misp --otx xxxxxx --server http://mis_server/ --misp xxxxxx -v -a --discover-tags -c otx-misp.ini -w -u
```
('-w', writes the ini file, '-u', updates the timestamp of last import in this file)

Next calls would be:
```
root@misp:~# otx-misp -c otx-misp.ini
```
