### ISSUE TITLE
global name 'jsonschema' is not defined

### ISSUE THREAD

**Issue by abaykal** [gcrahay/otx_misp#6]
otx-misp -o xxxxxx -m xxxxxxx -s https://xxxxxxx/ --timestamp 2016-05-17T07:07:35 -w -vvv 

When running the above command, it works with -d option and displays the content

however, when I remove -d, it give me the following error:
global name 'jsonschema' is not defined

**Comment by gcrahay** [comment]
Seems to be a PyMISP related error. I'll investigate...

**Comment by abaykal** [comment]
if it helps, I am using debian wheezy

**Comment by gcrahay** [comment]
There were some issues with the current PyMISP versions. I upgraded the otx-misp package to 1.1 and tested it on Wheezy, it should work now.

Steps on a fresh Wheezy install:

```bash
root@wheezy:~# apt-get install python-pip
root@wheezy:~# pip install virtualenv

debian@wheezy:~$ virtualenv env-wheezy
debian@wheezy:~$ . env-wheezy/bin/activate
(env-wheezy) debian@wheezy:~$ pip install otx-misp
(env-wheezy) debian@wheezy:~$ otx-misp -c otx.ini -vvv
```

**Comment by gcrahay** [comment]
Should be resolved, now.
