### ISSUE TITLE
Polling Events without Attributes - This event doesn't have any attributes visible to you.

### ISSUE THREAD

**Issue by CQRuu** [gcrahay/otx_misp#7]
Hi, 

I've been using an otx-misp script to poll from OTX and push to MISP for the past few months. However, recently, I realised that the OTX events were added in MISP without any attributes (from some time in 2017 Jan onwards). The message I received in my OTX event was:

> Attribute warning: This event doesn't have any attributes visible to you. Either the owner of the event decided to have a specific distribution scheme per attribute and wanted to still distribute the event alone either for notification or potential contribution with attributes without such restriction. Or the owner forgot to add the attributes or the appropriate distribution level. If you think there is a mistake or you can contribute attributes based on the event meta-information, feel free to make a proposal.

I have not made any modifications to the otx-misp script, and the OTX events in OTX alienvault do have attributes. 

Is there anything I'm missing out / new modifications I need to include?

My otx-misp script (from months ago):

`otx-misp -o <otx-key>  -s <misp-url> -m <misp-key> -t $(date -d "1 day ago" '+%Y-%m-%d')T00:00:00Z`

![otx-no-attributes](https://cloud.githubusercontent.com/assets/9025937/21879722/a3c06d24-d8d5-11e6-9180-110f755b75d3.PNG)

**Comment by gcrahay** [comment]
Hi,

Can you post your versions of:
- otx-misp
- PyMISP
- MISP

**Comment by CQRuu** [comment]
otx-misp: 1.0.3
PyMISP: 2.4.56
MISP: 2.4.58

**Comment by CQRuu** [comment]
I've updated my version of otx-misp to version 1.1  with `pip install otx-misp --upgrade` and now I'm able to push the feeds (events and attributes) into MISP. Thanks for your help!

**Comment by CQRuu** [comment]
Hi, I'm afraid I've been getting the old error again. 

**Versions**
otx-misp: 1.1.1
PyMISP: 2.4.56
MISP: 2.4.67

**Error message:**

> Attribute warning: This event doesn't have any attributes visible to you. Either the owner of the event decided to have a specific distribution scheme per attribute and wanted to still distribute the event alone either for notification or potential contribution with attributes without such restriction. Or the owner forgot to add the attributes or the appropriate distribution level. If you think there is a mistake or you can contribute attributes based on the event meta-information, feel free to make a proposal
![image](https://cloud.githubusercontent.com/assets/9025937/23639446/c32cc654-0322-11e7-8d5c-20bc97e5cbf3.png)



On running my otx-misp script, it shows an additional message:
> 500 Server Error: Internal Server Error for url: http://[[my-ip]]/events


I'm able to see OTX events being added in but there are no attributes added.

![image](https://cloud.githubusercontent.com/assets/9025937/23639408/92fe9ed0-0322-11e7-9915-3b69d032c011.png)

**Comment by gcrahay** [comment]
I think PyMISP 2.4.56 is incompatible with MISP 2.4.67.

I have no error with:
Python: 2.7.9
otx-misp: 1.1.1
PyMISP: 2.4.68
MISP: 2.4.67 or 2.4.68

Crash with:
Python: 3.4.2
otx-misp: 1.1.1
PyMISP: 2.4.68
MISP:  2.4.67 or 2.4.68

No error with:
Python: 3.4.2
otx-misp: 1.1.1
PyMISP: 2.4.65 (recommended PyMISP version with MISP 2.4.67 and 2.4.68)
MISP: 2.4.67 or  2.4.68

You should upgrade your PyMISP version to 2.4.65.
